#!/bin/sh

# fix sorting order to avoid test failure
LC_COLLATE=C
export LC_COLLATE

text=../disambig/newdevtest.ascii
C=50

ngram-count -order 1 -text $text -write - | \
gawk 'NF == 2 && $2 >= 5 { print $1 }' > min5.vocab

ngram-class -debug 1 \
	-vocab min5.vocab -noclass-vocab noclass.vocab \
	-text ../disambig/newdevtest.ascii \
        -incremental -numclasses $C \
        -classes classes.raw

# remove some randomness by renaming classes to
# correspond to word sorting order

sort -k 3,3 classes.raw | \
gawk '{ if (!($1 in classes)) { classes[$1] = 1; printf "%s CLASS-%05d\n", $1, ++nc; } }' | \
sort -k 1,1 > classes.map

sort -k 1,1 classes.raw | \
join -o 2.2,1.2,1.3 - classes.map | \
sort -k 3,3

rm classes.raw classes.map min5.vocab

