.\" $Id: TEMPLATE.5,v 1.1 1999/10/18 21:09:32 stolcke Exp $
.TH XXX 5 "$Date: 1999/10/18 21:09:32 $" "SRILM File Formats"
.SH NAME
XXX \- XXX
.SH SYNOPSIS
.B XXX
.SH DESCRIPTION
.SH "SEE ALSO"
.SH BUGS
.SH "AUTHOR (of this page)"
Andreas Stolcke <stolcke@speech.sri.com>.
.br
Copyright 1999 SRI International
