#!/bin/sh

# set LC_COLLATE to make character ranges in add-pauses-to-pfsg work
LC_COLLATE=C
export LC_COLLATE

ngram-count -debug 1 -text gb.test.txt -lm - \
	-wbdiscount1 -wbdiscount2 -wbdiscount3 | \
make-ngram-pfsg | \
add-pauses-to-pfsg 


