.\" $Id: TEMPLATE.3,v 1.3 1999/10/16 21:40:38 stolcke Exp $
.TH XXX 3 "$Date: 1999/10/16 21:40:38 $" SRILM
.SH NAME
XXX \- XXX
.SH SYNOPSIS
.B #include <XXX.h>
.SH DESCRIPTION
.SH TYPES
.SH CONSTANTS
.SH FUNCTIONS
.SH "SEE ALSO"
.SH BUGS
.SH AUTHOR
Andreas Stolcke <stolcke@speech.sri.com>.
.br
Copyright 1999 SRI International
