.\" $Id: TEMPLATE.3,v 1.1 1996/07/12 19:00:28 stolcke Exp stolcke $
.TH XXX 3 "$Date: 1996/07/12 19:00:28 $" SRILM
.SH NAME
XXX \- XXX
.SH SYNOPSIS
.B #include <XXX.h>
.SH DESCRIPTION
.SH TYPES
.SH CONSTANTS
.SH FUNCTIONS
.SH "SEE ALSO"
.SH BUGS
.SH AUTHOR
Andreas Stolcke <stolcke@speech.sri.com>.
.br
Copyright 1995, 1996 SRI International
