#!/usr/local/bin/gawk -f
#
# nbest2-to-nbest1 --
#	Convert Decipher NBestList2.0 format to NBestList1.0 format
#
# $Header: /home/spot71/srilm/devel/utils/src/RCS/nbest2-to-nbest1,v 1.1 1997/02/21 20:20:09 stolcke Exp $
#
BEGIN {
	magic1 = "NBestList1.0";
	magic2 = "NBestList2.0";
}
NR == 1 {
	if ($0 != magic2) {
		print "Input not in " magic2 " format" > "/dev/stderr";
		exit 1;
	}
	print magic1;
	next;
}
{
	line = $1;
	for (i = 2; i <= NF; i += 11) {
		line = line " " $i;
	}
	print line;
}
