#!/bin/sh
#
# rescore-nbest-pass1 --
#	pass1 of rescore-nbest
#
# $Header: /export/d/stolcke/project/srilm/src/scripts/RCS/rescore-nbest,v 1.1 1995/08/10 05:53:49 stolcke Exp stolcke $
#

if [ $# -lt 1  ]; then
	echo "usage: $0: nbest-file-list" >&2
	exit 1
fi

filelist="$1"
shift

#
# STRATEGY:
#	Concatenate hyps for all nbest list, record number of hyps for
#		each file in the output stream
#	Strip hyp ids, !SENT_START, !SENT_END 
#	Feed to ngram -ppl (using lm-options)
#	Parse ngram output into lm scores and deposit into target files
#

escape="***FILE:"

cat $filelist | ( \
while read filename; do
	set -e
	numhyps=`wc -l < $filename`
	echo "$escape `basename $filename .trans`.score $numhyps"
	sed \
		-e 's/^ *([^ ]*) //' \
		-e 's/!SENT_START //' \
		-e 's/!SENT_END //' \
		$filename
done
) 
