#
#    File:   Makefile.example
#    Author: The SRI DECIPHER (TM) System
#    Date:   Thu Sep  9 12:04:47 1993
#
#    Description:
#	This is the example makefile to start from when adding new
#       modules to the DECIPHER System.  To use this makefile, first
#       copy it to your directory as the file "Makefile".  Second,
#       replace the word "Example" in the text below with the real name
#	of your library.  Next replace the the example filenames with
#	the names of your actual declarations and source files in the
#	appropriate variable definitions.  Finally clean up by deleting
#	any lines not relevant to your module and updating this header
#       to describe your new module.  Do not forget to use the proper
#       RCS keywords!
#
#    Copyright (c) 1993, SRI International.  All Rights Reserved.
#
#    RCS ID: $Id: Makefile.example,v 1.8 1996/07/23 19:47:12 stolcke Exp $
#
#    $Log: Makefile.example,v $
#    Revision 1.8  1996/07/23 19:47:12  stolcke
#    include std srilm libraries in LIBRARIES
#
#    Revision 1.7  1996/06/10 05:31:27  stolcke
#    parametrize ar command
#
#    Revision 1.6  1995/11/13 23:29:16  stolcke
#    added SRILM, MACHINE_TYPE setting
#
#    Revision 1.5  1995/06/24 21:19:52  stolcke
#    run ar output through c++filt
#
#    Revision 1.4  1995/06/19 02:08:21  stolcke
#    added C++ support
#
#    Revision 1.3  1994/12/03 23:50:19  decipher
#    Updated to use new release-* targets.
#
# Revision 1.2  1994/03/09  02:34:00  psi
# Updated to work better with "make depend".
#
# Revision 1.1  1993/09/09  20:15:31  decipher
# Initial revision
#
#

DECIPHER = $(SRILM)
MACHINE_TYPE := $(shell $(DECIPHER)/bin/machine-type)

# Include common DECIPHER (TM) variable definitions.
include $(DECIPHER)/common/Makefile.common.variables


# Define variables.

# Example Library declarations files.

EXTERNAL_LIB_HEADERS = $(SRCDIR)/example-external.h

INTERNAL_LIB_HEADERS = $(SRCDIR)/example-internal.h

# Example Library source files.
LIB_SOURCES = $(SRCDIR)/example.c

# Example Library object files.
LIB_OBJECTS = $(patsubst $(SRCDIR)/%.cc,$(OBJDIR)/%.o,\
		$(patsubst $(SRCDIR)/%.c,$(OBJDIR)/%.o,$(LIB_SOURCES)))


# Example Library.
LIBRARY = $(OBJDIR)/libexample.a

# Example programs.
PROGRAM_NAMES = example-program

PROGRAMS = $(PROGRAM_NAMES:%=$(BINDIR)/%)

PROGRAM_SOURCES = $(foreach prog,$(PROGRAM_NAMES),\
			$(wildcard $(SRCDIR)/$(prog).c) \
			$(wildcard $(SRCDIR)/$(prog).cc))
PROGRAM_OBJECTS = $(PROGRAM_NAMES:%=$(OBJDIR)/%.o)


# Libraries to be linked with the Example programs.
# (include standard LM and helper libraries)
LIBRARIES = $(LIBRARY) \
	    -loolm \
	    -ldstruct \
	    -lmisc \
	    $(ADDITIONAL_LIBRARIES)

# All of the types of files.

ALL_HEADERS = $(EXTERNAL_LIB_HEADERS) \
	      $(INTERNAL_LIB_HEADERS)

ALL_SOURCES = $(LIB_SOURCES) \
	      $(PROGRAM_SOURCES)

ALL_OBJECTS = $(LIB_OBJECTS) \
	      $(PROGRAM_OBJECTS)

ALL_LIBRARIES = $(LIBRARY)

ALL_PROGRAMS = $(PROGRAMS)

ALL_PROGRAM_NAMES = $(PROGRAM_NAMES)


# Define pseudo-targets.


# Make sure the library does not get deleted if the make is interrupted.
.PRECIOUS:	$(LIBRARY)


# Define targets.


all:	$(PROGRAMS)

$(LIBRARY):	$(LIB_OBJECTS)
	$(ARCHIVE) $@ $^ $(DEMANGLE_FILTER)
	$(RANLIB) $@ $(DEMANGLE_FILTER)


# Variables and Targets for released system

EXPORTED_HEADERS   = $(EXTERNAL_LIB_HEADERS)
EXPORTED_LIBRARIES = $(LIBRARY)
EXPORTED_PROGRAMS  = $(PROGRAMS)

release:	release-headers release-libraries release-programs

# Include common DECIPHER (TM) target definitions.
include $(DECIPHER)/common/Makefile.common.targets
