#!/bin/sh

ngram -debug 1 \
	-lm ../ngram-count-gt/swbd.3bo.gz -lambda 0.3 \
	-mix-lm ../class-ngram-simple/train-400classes.3bo.gz \
	-classes ../class-ngram-simple/train+unk.400classes.gz \
	-mix-lm2 ../ngram-count-gt/swbd.3bo.gz -mix-lambda2 0.3 \
	-bayes 0 \
	-ppl ../ngram-count-gt/eval97.text


