.\" $Id: disambig.1,v 1.22 2003/01/28 17:36:50 stolcke Exp $
.TH disambig 1 "$Date: 2003/01/28 17:36:50 $" "SRILM Tools"
.SH NAME
disambig \- disambiguate text tokens using an N-gram model
.SH SYNOPSIS
.B disambig 
[\c
.BR \-help ]
.I option
\&...
.SH DESCRIPTION
.B disambig
translates a stream of tokens from a vocabulary V1 to a corresponding stream
of tokens from a vocabulary V2, 
according to a probabilistic, 1-to-many mapping.
Ambiguities in the mapping are resolved by finding the V2 sequence with
the highest posterior probability given the V1 sequence.
This probability is computed from pairwise conditional probabilities P(V1|V2),
as well as a language model for sequences over V2.
.SH OPTIONS
.TP
.B \-help
Print option summary.
.TP
.BI \-text " file"
Specifies the file containing the V1 sentences.
.TP
.BI \-map " file"
Specifies the file containing the V1-to-V2 mapping information.
Each line of
.I file
contains the mapping for a single word in V1:
.br
	w1	w21 [p21] w22 [p22] ...
.br
where
.I w1
is a word from V1, which has possible mappings
.IR w21 ,
.IR w22 ,
\&... from V2.
Optionally, each of these can be followed by a numeric string for the
probability
.IR p21 ,
which defaults to 1.
The number is used as the conditional probability P(\fIw1\fP|\fIw21\fP),
but the program does not depend on these numbers being properly normalized.
.TP
.BI \-text\-map " file"
Processes a combined text/map file.
The format of
.I file
is the same as for
.BR \-map ,
except that the 
.I w1
field on each line is interpreted as a word 
.I token 
rather than a word 
.IR type .
Hence, the V1 text input consists of all words in column 1 of
.I file
in order of appearance.
This is convenient if different instances of a word have different mappings.
There is no implicit insertion of begin/end sentence tokens in this 
mode.  Sentence boundaries should be indicated explicitly by 
lines of the form
.br
	</s>	</s>
.br
	<s>	<s>
.br
.TP
.B \-scale
Interpret the numbers in the mapping as P(\fIw21\fP|\fIw1\fP).
This is done by dividing probabilities by the unigram probabilities of
.IR w21 ,
obtained from the V2 language model.
.TP
.B \-logmap
Interpret numeric values in map file as log probabilities, not probabilities.
.TP
.BI \-lm " file"
Specifies the V2 language model as a standard ARPA N-gram backoff model file
.BR ngram-format (5).
The default is not to use a language model, i.e., choose V2 tokens
based only on the probabilities in the map file.
.TP
.BI \-order " n"
Set the effective N-gram order used by the language model to
.IR n .
Default is 2 (use a bigram model).
.TP
.BI \-lmw " W"
Scales the language model probabilities by a factor 
.IR W .
Default language model weight is 1.
.TP
.BI \-mapw " W"
Scales the likelihood map probability by a factor
.IR W .
Default map weight is 1.
Note: For Viterbi decoding (the default) it is equivalent to use
.BI \-lmw " W"
or 
.BI \-mapw " 1/W",
but not for forward-backward computation.
.TP
.B \-tolower1
Map input vocabulary (V1) to lowercase, removing case distinctions.
.TP
.B \-tolower2
Map output vocabulary (V2) to lowercase, removing case distinctions.
.TP
.B \-keep-unk
Do not map unknown input words to the <unk> token.
Instead, output the input word unchanged.
This is like having an implicit default mapping for unknown words to
themselves, except that the word will still be treated as <unk> by the language
model.
Also, with this option the LM is assumed to be open-vocabulary
(the default is close-vocabulary).
.TP
.B \-no-eos
Do no assume that each input line contains a complete sentence.
This prevents end-of-sentence tokens </s> from being appended automatically.
.TP
.B \-continuous
Process all words in the input as one sequence of words, irrespective of
line breaks.
Normally each line is processed separately as a sentence.
V2 tokens are output one-per-line.
This option also prevents sentence start/end tokens (<s> and </s>)
from being added to the input.
.TP
.B \-fb
Perform forward-backward decoding of the input (V1) token sequence.
Outputs the V2 tokens that have the highest posterior probability,
for each position.
The default is to use Viterbi decoding, i.e., the output is the
V2 sequence with the higher joint posterior probability.
.TP
.B \-fw-only
Similar to 
.BR \-fb ,
but uses only the forward probabilities for computing posteriors.
This may be used to simulate on-line prediction of tags, without the
benefit of future context.
.TP
.B \-totals
Output the total string probability for each input sentence.
.TP
.B \-posteriors
Output the table of posterior probabilities for each 
input (V1) token and each V2 token, in the same format as
required for the
.B \-map
file.
If
.B \-fb
is also specified the posterior probabilities will be computed using
forward-backward probabilities; otherwise an approximation will be used
that is based on the probability of the most likely path containing 
a given V2 token at given position.
.TP
.BI \-nbest " N"
Output the
.I N
best hypotheses instead of just the first best when
doing Viterbi search.
If
.IR N >1,
then each hypothesis is prefixed by the tag
.BI NBEST_ n " " x ,
where
.I n
is the rank of the hypothesis in the N-best list and
.I x 
its score, the negative log of the combined probability of transitions
and observations of the corresponding HMM path.
.TP
.BI \-write-vocab1 " file"
Writes the input vocabulary from the map (V1) to
.IR file .
.TP
.BI \-write-vocab2 " file"
Writes the output vocabulary from the map (V2) to
.IR file .
The vocabulary will also include the words specified in the language model.
.TP
.BI \-write-map " file"
Writes the map back to a file for validation purposes.
.TP
.B \-debug
Sets debugging output level.
.PP
Each filename argument can be an ASCII file, or a compressed
file  (name  ending  in  .Z  or  .gz),  or ``-'' to indicate
stdin/stdout.
.SH BUGS
The
.B \-continuous
and 
.B \-text\-map
options effectively disable
.BR \-keep-unk ,
i.e., unknown input words are always mapped to <unk>.
.SH "SEE ALSO"
ngram-count(1), hidden-ngram(1), training-scripts(1), ngram-format(5).
.SH AUTHOR
Andreas Stolcke <stolcke@speech.sri.com>,
.br
Anand Venkataraman <anand@speech.sri.com>.
.br
Copyright 1995\-2002 SRI International
