#!/bin/sh

flags="-no-virtual-begin-sentence -no-virtual-end-sentence"

fngram-count $flags -debug 2 -factor-file test.flm -text ../fngram-count/ch_lm_train100.noamp.decomposed.txt.gz -write-counts -lm -unk -nonull

ngram -debug 0 -order 2 -factored -lm test.flm -ppl ../fngram-count/ch_lm_dev.noamp.decomposed.txt.gz -unk -nonull

rm -f dev.count.gz dev.lm.gz

